# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ynov Legends' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ynov Legends
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'

  target 'Ynov LegendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ynov LegendsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
